package com.example.veronica.areteapp;

import java.util.ArrayList;
import java.util.Arrays;

public class Questions
{
	private ArrayList<String> questionList;

	public Questions()
	{
		this.questionList = new ArrayList<String>(Arrays.asList(
				"What do you care about deeply, and why?",
				"List what your top three strengths are.",
				"Reflect on a societal problem for which you would like to contribute a solution.",
				"When you have had great day, what was it you were doing and what were you not doing?",
				"How can you be more organized and disciplined?",
				"Identify the times you are your own worst enemy.",
				"Try apologizing today without adding blame.",
				"Ask yourself what actions have I taken to further my mission.",
				"Write your plan for tomorrow and review it the day after tomorrow.",
				"Strike up a conversation with a complete stranger. What did you learn?",
				"What are you good at?",
				"How do you want others to see yourself?",
				"What adversities have you overcome?",
				"Who are the most important people in your life and why?",
				"What’s something that’s been on your bucket list for a while now?",
				"Am I putting enough effort into my relationships?",
				"What situations make you feel terrible, and what do they have in common? ",
				"What activities are you doing when it feels like time flies by?",
				"If you changed nothing, what would your life look like three months from now? How does this make you feel?",
				"If not now, then when?",
				"Have I made someone smile today?",
				"Would I steal to feed a starving child?",
				"Which is worse: failing or never trying?",
				"You really wish others knew this about you…",
				"Write about your first love — whether a person, place or thing.",
				"When do you feel the most energized?",
				"Make a list of everything you’d like to say no to.",
				"Make a list of everything you’d like to say yes to.",
				"What’s surprised you the most about your life or life in general?",
				"What can you learn from your biggest mistakes?",
				"Name what is enough for you.",
				"What does unconditional love look like for you?",
				"If your body could talk, what would it say?",
				"What is the kindest thing you can do for yourself when you are in emotional pain?",
				"“Write about a moment experienced through your body. Making love, making breakfast, going to a party, having a fight, an experience you’ve had or you imagine for your character. Leave out thought and emotion, and let all information be conveyed through the body and senses.”",
				"The words I’d like to live by are…",
				"I couldn’t imagine living without…",
				"My favorite way to spend the day is…",
				"If I could talk to my teenage self, the one thing I would say is…",
				"The two moments I’ll never forget in my life are… Describe them in great detail, and what makes them so unforgettable.",
				"Make a list of 5 things that make you smile.",
				"What do I want most in life?",
				"What is life calling of you?",
				"Which is worse: failing or never trying?",
				"If I try to fail, and succeed, what have I done?",
				"What’s the one thing I’d like others to remember about you at the end of my life?",
				"Does it really matter what others think about you?",
				"To what degree have I actually controlled the course my life has taken?",
				"When it’s all said and done, what will I have said more than I’ve done?",
				"What’s in your way towards your dream?",
				"Has your personality changed since childhood? If so, why?",
				"What quality do you admire the most about yourself?",
				"If you could change your hair colour for a day, what would it be to?",
				"How do you make a decision? By intuition or logical analysis?",
				"Where is your favorite spot to relax and get away for a while?",
				"If you could be the opposite sex for a day, what would you?",
				"What’s one thing that you gave a reaction to that didn’t deserve it?",
				"What’s something your role model has done that you want to achieve as well?",
				"Is it possible to learn old dogs tricks?",
				"What did you love doing as a child that you don’t do anymore?",
				"How much money is enough?",
				"If money didn’t matter, what would you do for a living?",
				"When was the last you told your mom you love her?",
				"Do you like change or not?",
				"What made you smile today?",
				"How many hours of sleep do you get in general?",
				"Do you learn from bad situations or regretting them?",
				"What do you think about the words “if only”?",
				"If you had 2 % more of courage, what would you do?",
				"What is worse: Never succeed, or never try?",
				"What is your best friends best ability?",
				"Who influenced you when you were younger, and why?",
				"How can you become a role model?",
				"Are you introverted or extroverted? ",
				"Do you engage in activities to escape your reality?",
				"What do you think you could never, ever give up?",
				"Who (or what) always makes you laugh?",
				"How do you spend the majority of your time?",
				"Are you good at being in the present moment?",
				"What was the last thing you purchased?",
				"Do you often remember your dreams when you wake?",
				"What’s on your to-do list that never gets done?",
				"Would you move to another country?",
				"How would your best friend describe you?",
				"Do you consider your childhood a happy one?",
				"When did you last feel disappointed?",
				"Do you have any (or many) guilty pleasures?",
				"How do you feel when faced with change?",
				"Do you believe in giving second chances?",
				"Do you always say what’s on your mind?",
				"How do you cope with stress?",
				"What would you tell your younger self?",
				"How often do you learn new things?",
				"Do you enjoy spending time with others?",
				"What is your favorite time of day?",
				"How often do you ask others for help?",
				"Are you good at establishing boundaries?",
				"What’s the best day you’ve had so far?",
				"Do you frequently make wishes?",
				"What would your ideal career consist of?",
				"Where is your favorite place to be?",
				"Do you say “yes” or “no” more often?",
				"What’s the best advice you’ve ever received?",
				"How open are you with others?",
				"What is currently worrying you?",
				"Which sense do you use the most?",
				"How would you define the meaning of life?",
				"What questions are you asked often?",
				"When was the last time you made a change?",
				"Do you enjoy talking about yourself?",
				"Who do you call when you’re upset?",
				"How often do you procrastinate?",
				"Do you believe people can really change?",
				"When did you last see the sun rise?",
				"Do you think time heals all wounds?",
				"What is your relationship with technology?",
				"Are you good at letting things go?",
				"Do you prefer morning, afternoon, or night?",
				"What does the word “self-love” mean to you?",
				"Are you living your life for yourself?",
				"What would you like to be remembered for?",
				"Do you feel connected to your culture?",
				"What’s the strangest thing you’ve experienced?",
				"How would you describe your personal style?",
				"What do you like/dislike about your gender?",
				"Do you have difficulty sleeping?",
				"What do you want to learn more about?",
				"Can you accept compliments easily?",
				"What can you do really, really well?",
				"Would you like to live in a different decade?",
				"What do you enjoy about adulthood?",
				"Do you think you have a big imagination?",
				"What’s the biggest risk you’ve taken?",
				"Could you live without the internet?",
				"Why do you get out of bed each day?",
				"When did you last make a new friend?",
				"Do you think your ego gets in the way?",
				"What can’t you go a day without thinking about?"
		));
	}

	public String getNextQuestion(int index)
	{
		index+=1;
		return questionList.get(index % questionList.size());
	}
}
